door_server_node:
  ros__parameters:
    update_rate:                    30
    check_diff_image:               false
    check_labeling_hough_image:     false
    check_kmeans_hough_image:       false
    check_kmeans_clustering_image:  false
    check_updated_image:            false
    check_door_state_image:               true